Sb/drive system
StuyPulse/Edwin pull request #18
Opened 2020-02-01 21:58 UTC by Sam-Belliveau

This is pretty much done, we just need to get the ports and calculate values, which we can't do until we have a drive train

2020-02-04 23:59 UTC, Sam-Belliveau commented
Here is where the newbies fill in the gaps, I just provided a (fairly large sorry) template with all the complicated stuff

2020-02-05 21:19 UTC, PrathamRawat requested changes
A few things need to be changed
Please use standard Java naming conventions instead of the m / k convention (the big one)
I have qualms merging this in unless Tahsin and Kevin both also give their approval of this structure
I'll do a deeper reading of the code structure once that is done

2020-02-05 21:19 UTC, PrathamRawat commented on src/main/java/com/stuypulse/robot/subsystems/Drivetrain.java
> +     * Sets drivetrain into high gear
Low

2020-02-05 21:19 UTC, PrathamRawat commented on src/main/java/com/stuypulse/robot/subsystems/Drivetrain.java
> +     * Sets drivetrain into low gear
High

2020-02-08 18:54 UTC, PrathamRawat commented
Merge master into your branch and fix merge conflicts

2020-02-10 21:57 UTC, PrathamRawat approved these changes

2020-02-10 21:57 UTC, merged