wn/chute
StuyPulse/Edwin pull request #21
Opened 2020-02-05 21:56 UTC by selym3

To Mr. Pratham,

It would be greatly appreciated if you could take the time out of your day to analyze this branch.

Sincerely,
Myles

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/Constants.java
> +	double CHUTE_LIFT_UP_SPEED = -1;
Separate ports and constants into two different sections.

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteDownCommand.java
> +    /*@Override
Why is this commented out?

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteIntakeCommand.java
> +    public void end(boolean interrupted) {
Why is this commented out?

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteUpCommand.java
> +        chute.stopChute();
Why is this commented out too?

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/subsystems/Chute.java
> +    public double getTicks() {
When do you use these three methods?

2020-02-06 02:39 UTC, rmui10 commented on vendordeps/Phoenix.json
> +{
When do you need this?

2020-02-06 02:39 UTC, rmui10 commented on vendordeps/navx_frc.json
> +{
When do you need this?

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteIntakeCommand.java
> +        if (previousValue != RobotContainer.gamepad.getRawDPadDown()) {
Why do you need this part? OI (configuring commands to buttons) should already do this for you

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteIntakeCommand.java
> +                chute.stopChute();
You don't need this here; just put it in end.

2020-02-06 02:39 UTC, rmui10 commented on src/main/java/com/stuypulse/robot/commands/ChuteUpCommand.java
> +        // Use addRequirements() here to declare subsystem dependencies.
Delete this comment

2020-02-06 02:42 UTC, rmui1 submitted a review, later dismissed
Oops, forgot to mention this before, but merge master into your branch and fix the merge conflicts

2020-02-07 04:00 UTC, PrathamRawat commented
I disagree with some of Renee’s comments, we’ll talk about it in person

2020-02-11 21:52 UTC, PrathamRawat requested changes

2020-02-11 21:52 UTC, PrathamRawat commented on src/main/java/com/stuypulse/robot/commands/ChimneyStopCommand.java
> +public class ChimneyStopCommand extends CommandBase {
Should be an instant command

2020-02-11 21:52 UTC, PrathamRawat commented on src/main/java/com/stuypulse/robot/utils/NeoEncoder.java
> +public final class NeoEncoder {
This file should be removed

2020-02-11 21:59 UTC, selym3 commented on src/main/java/com/stuypulse/robot/commands/ChimneyStopCommand.java
> +public class ChimneyStopCommand extends CommandBase {
Review in code review 2

2020-02-11 22:00 UTC, PrathamRawat approved these changes
Good work guys

2020-02-11 22:02 UTC, merged